### cities request ####
POST  http://localhost:5003/api/cities
Content-Type: application/json


{
      "cityName": "Paris",
      "cityCount": 3333
}
###
GET http://localhost:5003/api/cities
Content-Type: application/json

###

GET http://localhost:5003/api/cities/3b8e4fa5-27eb-4a45-b6f7-b94f30a10c4a
Content-Type: application/json

